[package]
name = "dubit/debug-tools"
version = "0.3.0"                                             # remember to update version in Constants.lua
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
license = "MIT"
description = "An expandable Debug Tools interface with several features."

exclude = ["**"]
include = ["Source", "Source/*", "default.project.json", "wally.toml"]
