site_name: Roblox Dubit Tools
site_url: https://dubit.github.io/roblox-dubit-tools/
site_author: dubit
repo_name: dubit/roblox-dubit-tools
repo_url: https://github.com/dubit/roblox-dubit-tools
docs_dir: Docs

theme:
  favicon: img/favicon.ico
  name: material
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.copy
    - content.code.annotate
    - content.code.select

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/api.css

nav:
  - 'index.md'
  - Allocation Pool:
    - 'packages/allocation_pool.md'
    - 'api/allocation_pool.md'
  - Anticheat:
    - 'packages/anticheat.md'
    - 'api/anticheat.md'
  - Bolt:
    - 'packages/bolt.md'
    - 'api/bolt.md'
  - Debug Tools:
    - 'packages/debug_tools.md'
  - Dubit Store:
    - 'packages/dubit_store.md'
    - 'api/dubit_store.md'
  - Dubit Utils:
    - 'packages/dubit_utils.md'
    - 'api/dubit_utils.md'
  - Engagements:
    - 'packages/engagements.md'
    - 'api/engagements.md'
  - Event Tracker:
    - 'packages/event_tracker.md'
    - 'api/event_tracker.md'
  - Sequence Animator:
    - 'packages/sequence_animator.md'
    - 'api/sequence_animator.md'
  - Simple Store:
    - 'packages/simple_store.md'
    - 'api/simple_store.md'