[package]
name = "dubit/dubit-pickups"
version = "0.2.0"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
license = "MIT"

description = "A simple to use Pickup System"

exclude = ["**"]
include = ["Source", "Source/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
Signal = "sleitnick/signal@2.x.x"