[package]
name = "dubit/bolt"
version = "2.0.0"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
license = "MIT"

description = "A networking library that focuses on type safety"

exclude = ["**"]
include = ["Source", "Source/*", "default.project.json", "wally.toml"]
