[package]
name = "dubit/ugc-toolkit"
version = "0.1.0"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
license = "MIT"

description = "A suite/library of functions that enable developers to implement common functions often assigned to 3d podiums/UGCs in experiences."

exclude = ["**"]
include = ["Source", "Source/*", "default.project.json", "wally.lock", "wally.toml"]

[dev-dependencies]
TestEz = "roblox/testez@0.4.1"