[package]
name = "dubit/dubit-utils"
version = "1.0.0"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
license = "MIT"

description = "A library with common utility data / functions."

exclude = ["**"]
include = ["Source", "Source/*", "default.project.json", "wally.toml"]
