[package]
name = "dubit/sequence-animator"
version = "0.1.0"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
license = "MIT"

description = "A library for creating Keyframe Sequences"

exclude = ["**"]
include = ["Source", "Source/*", "default.project.json", "wally.toml"]