[package]
name = "dubit/totalizers"
version = "1.0.0"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
license = "MIT"

description = "The community goals/totaliser tool is a tool that allows us to create some sort of value that can be written to, and read from - from all Servers within a Roblox experience."

exclude = ["**"]
include = [
	"Source",
	"Source/*",
	"default.project.json",
	"wally.lock",
	"wally.toml",
]

[dependencies]
Signal = "sleitnick/signal@^2.0.3"
DubitUtils = "dubit/dubit-utils@^1.0.0"
